### PR TITLE
chore: better configuration for our school using nx

### PR DESCRIPTION
**Pull request by JonathanGeoffroy**
Upgrade nx to 13.x.x (latest stable release)
Upgrade Rect to 18.x.x (latest stable release)
Add nx custom commands for docs

### CODE REVIEW

**Review by VictorJozwicki — APPROVED** [review]
Looks good for me even though I don't know any config ^^'

**Comment by JonathanGeoffroy** [comment]
@VictorJozwicki  Thank you for your review 👍 
Did you have a chance to pull the repo and run few commands, such as `npm run start` or `npm run slides` ?
Checking that everything works great on a fresh computer would be very helpful for this kind of config stuff.

**Comment by VictorJozwicki** [comment]
@JonathanGeoffroy Want me to try something else as well ?
Install OK
npm run start OK
image

npm run slides OK
image

**Comment by JonathanGeoffroy** [comment]
@VictorJozwicki perfect! Thank you for your time.

**Pull request merged**
