### PR TITLE
feat(solution): implement people list

### PR DESCRIPTION
**Pull request by JonathanGeoffroy**
Display people list in homepage.
Configure testing (unit, e2e).
Configure custom nx commands (start, develop, test, e2e).
Configure design library.

### CODE REVIEW

**Review by VictorJozwicki — APPROVED** [review]
Didn't even know you could do something like `className={styles.container}` :o

**Comment by JonathanGeoffroy** [comment]
> Didn't even know you could do something like `className={styles.container}` :o

It's all thanks to [css modules](https://create-react-app.dev/docs/adding-a-css-modules-stylesheet) preprocessing. 
Maybe we should explain this (the fact that naming a file "*.module.[s]css") a little bit on our school ? Especially because it's causing className rewriting to avoid css className clashes (take a look at the name of your class in your dev tool :) )

What do you think about it @VictorJozwicki ?

**Comment by VictorJozwicki** [comment]
@JonathanGeoffroy Isn't it specific to CRA though ? Should we center the school around the possibilities CRA scripts gives us ?
Interesting feature nonetheless that allows to write without caring about class clashes.

**Comment by JonathanGeoffroy** [comment]
> @JonathanGeoffroy Isn't it specific to CRA though ? Should we center the school around the possibilities CRA scripts gives us ? Interesting feature nonetheless that allows to write without caring about class clashes.

Yes it is, in a way. It's related to how CRA bootstrap your project. 
So it's not exactly ReactJS related to be honest. That's the reason why I don't know what to think about explaining this feature. It's actually solving a lot of problems in real enterprise apps, IMO.

**Comment by JonathanGeoffroy** [comment]
That make me think about the complexity [Nx](https://nx.dev/) brings to our training : 
 * Does creating a `lib` bring complexity ? Or does it  helps to split complexity in exercices (we used to   create helpers functions / components so that students don't have to handle the whole complexity in the same exercice). 
  * in `.env` file (and associated), CRA uses "REACT_APP" as the prefix, but NX overwrite it to "NX_"
  * We use  nx custom command to start the app and (future) exercises, but it will be different if stutdents start an app using CRA.

**Comment by VictorJozwicki** [comment]
> 

I would tend to agree with you. I believe React projects outside of CRA are used for more specific cases and users are aware (or should be at least) of the advantages/disadvantages of not using CRA.

**Comment by VictorJozwicki** [comment]
> * Does creating a `lib` bring complexity ? Or does it  helps to split complexity in exercices (we used to   create helpers functions / components so that students don't have to handle the whole complexity in the same exercice).

I think we can abstract some part to either later stages or simply explaining that the logic behind it isn't worth the time to explain ?

> * in `.env` file (and associated), CRA uses "REACT_APP" as the prefix, but NX overwrite it to "NX_"
> * We use  nx custom command to start the app and (future) exercises, but it will be different if students start an app using CRA.

It depends if we consider that students should understand that during the training, we use nx for ease of use, but they're welcome to use npm, yarn or any other to start the CRA scripts.

**Comment by JonathanGeoffroy** [comment]
Totally agree you in both subjects. I think Nx is a very good tool for our school, and trainer can explain Nx a little bit, or answer questions.

**Review by VictorJozwicki — APPROVED** [review]
Ok

**Pull request merged**
